### ISSUE TITLE
魔改舵机，舵机内部与驱动板如何接线？

### ISSUE THREAD

**Issue by tony2ty** [peng-zhihui/ElectronBot#100]

**Comment by leazer** [comment]
喏，画了个示意图 ， 旋转编码器和电机接线顺序需要跟软件匹配
![](https://i0.hdslb.com/bfs/album/dc2d778a93e6ae9dda06f72cd927241b4b472caa.png@1e_1c.webp)
![](https://i0.hdslb.com/bfs/album/3a7c4805ca09ba6aaff2f776ae57a3f7e3c8ee23.png@1e_1c.webp)

**Comment by tony2ty** [comment]
> 喏，画了个示意图 ， 旋转编码器和电机接线顺序需要跟软件匹配 ![](https://camo.githubusercontent.com/10ee56d873b8dcee86b7ac689e17922311fd5613167561983125be6e9d0b85be/68747470733a2f2f69302e6864736c622e636f6d2f6266732f616c62756d2f646332643737386139336536616539646461303666373263643932373234316234623437326361612e706e674031655f31632e77656270) ![](https://camo.githubusercontent.com/e06dc0e5314a80b3578e7f10dfc99d128041774337e5955308036a39b4a41d20/68747470733a2f2f69302e6864736c622e636f6d2f6266732f616c62756d2f336137633438303563613039626136616166663266373736616535376133663765336338656532332e706e674031655f31632e77656270)

谢谢，舵机没搞过，等拿到舵机拆开看看

**Comment by tony2ty** [comment]
已验证
