### ISSUE TITLE
注意！！舵机应该是3.7g不是4.3g的  T.T

### ISSUE THREAD

**Issue by leazer** [peng-zhihui/ElectronBot#108]
**注意！！！**
#60 **中推荐的链接要选择3.7g的舵机，不是4.3g的！**
在外形上两个相差还挺多了，我打印完要装配了，发现买错了。。。
![微信图片_20220323221111](https://user-images.githubusercontent.com/16811146/159719842-088acba6-cff9-4a88-8ed5-42e14dcd23ee.jpg)
![微信图片_20220323221116](https://user-images.githubusercontent.com/16811146/159719870-60f9b38e-9a47-45e8-8ccf-9aa3ace1adae.jpg)

这是结构中的样子
![微信截图_20220323221637](https://user-images.githubusercontent.com/16811146/159720200-7cbdce14-76ac-42b6-9ae0-7584c93898be.png)
另外，稚晖在README中提到3g舵机没毛病。。
![微信截图_20220323221916](https://user-images.githubusercontent.com/16811146/159720778-0ad610ec-edac-488b-aa27-811f004abce3.png)

各位，购买时注意下。。。

**Comment by simasure** [comment]
会不会是因为你没拆后盖

**Comment by leazer** [comment]
> 会不会是因为你没拆后盖

不是哦，看下面图：差异在减速箱，一个是平的 一个是凸起的。
![O1CN01ZppJvt1DZNoiaqewh_!!1090800230 jpg_400x400](https://user-images.githubusercontent.com/16811146/159837188-f164a12a-78c7-43c4-b96a-f710d4cdc61c.jpg)

**Comment by vincent-vinf** [comment]
![Screenshot_2022-03-24-12-37-15-93_149003a2d400f6a](https://user-images.githubusercontent.com/54889985/159843429-f9c21970-393d-4a4a-b81b-ecb2d069e6c2.jpg)


看视频是这种凸起的 减速箱

**Comment by leazer** [comment]
> ![Screenshot_2022-03-24-12-37-15-93_149003a2d400f6a](https://user-images.githubusercontent.com/54889985/159843429-f9c21970-393d-4a4a-b81b-ecb2d069e6c2.jpg)
> 
> 看视频是这种凸起的 减速箱

![微信截图_20220324125704](https://user-images.githubusercontent.com/16811146/159845331-c546b232-9941-49a9-a28c-b54e5f8f8d36.png)

感觉安装的不是4.7g的    囧

**Comment by simasure** [comment]
所以4.3也是那安装上去的,UP用的都是4.3

**Comment by leazer** [comment]
> 所以4.3也是那安装上去的,UP用的都是4.3

期待你的安装测试结果

**Comment by peng-zhihui** [comment]
是4.3的哦，后盖需要拆除，更换M1x10的螺丝固定舵机壳子

**Comment by qiudaoyuz** [comment]
底部壳体要拆掉，否则侧面导线也会影响安装。

**Comment by leazer** [comment]
> 是4.3的哦，后盖需要拆除，更换M1x10的螺丝固定舵机壳子

我今天也发现是我错了...可是舵机已经退货换了3.7克，不过看着尺寸还算合适..

**Comment by leazer** [comment]
@qiudaoyuz 
胳膊轴那个件安装的时候，有没有感觉有些干涉

**Comment by peng-zhihui** [comment]
舵机不同型号有些差异，有些零部件可能跟大家买的舵机有些许不匹配，因为我也是一次打印出来的当时来不及细调加工，大家可以自己根据实际情况做调整，也欢迎分享自己的BOM和优化过的模型，可以提交pr

**Comment by peng-zhihui** [comment]
另外肚子前面那个很细的结构杆是可以去掉的，其实不影响，固定不够稳的话可以使用热熔胶
