### ISSUE TITLE
linker error

### ISSUE THREAD

**Issue by Empolal** [peng-zhihui/ElectronBot#114]
如题，尝试过复制原本的makefile.txt。

![linker error](https://user-images.githubusercontent.com/50899823/160152021-86d5345e-5301-472f-95f7-9acff6fa6a81.png)

d:/progra~1/stmicr~1/gnu-to~1/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld.exe: error: linker script file 'D:/Document/Stm32/ElectronBot/STM32F405RGTx_FLASH.ld' appears multiple times
collect2.exe: error: ld returned 1 exit status
mingw32-make.exe[3]: *** [CMakeFiles\ElectronBot.elf.dir\build.make:976: ElectronBot.elf] Error 1
mingw32-make.exe[2]: *** [CMakeFiles\Makefile2:75: CMakeFiles/ElectronBot.elf.dir/all] Error 2
mingw32-make.exe[1]: *** [CMakeFiles\Makefile2:82: CMakeFiles/ElectronBot.elf.dir/rule] Error 2
mingw32-make.exe: *** [Makefile:117: ElectronBot.elf] Error 2

**Comment by coolflyreg** [comment]
仔细检查你的工程文件。连接器给出的错误已经很清晰了。
