### ISSUE TITLE
大家驱动装上了吗？

### ISSUE THREAD

**Issue by txp666** [peng-zhihui/ElectronBot#120]
想问下这个有两个未知设备，驱动也打不上正常吗？
![image](https://user-images.githubusercontent.com/52451470/160754041-bc27a755-8965-4f48-ab94-2a1438b74f17.png)

**Comment by peng-zhihui** [comment]
驱动在Tools文件夹里啊，仔细看readme说明

**Comment by txp666** [comment]
> 驱动在Tools文件夹里啊，仔细看readm
指定到文件夹更新驱动了，就显示无法安装

**Comment by peng-zhihui** [comment]
先仔细看一遍readme

**Comment by txp666** [comment]
ok感谢回复，我再研究研究

**Comment by watking** [comment]
我在取消非强制签名系统模式下，右键ElectronBot@PZH.inf 安装提示安装，但是并未提示安装成功，ElectronBot.inf安装成功了，但是并没有认出设备。

**Comment by peng-zhihui** [comment]
直接取消强制签名后右键更新驱动导航到文件夹就自动安装了
