### ISSUE TITLE
结构与 PCB 形状如何完美耦合

### ISSUE THREAD

**Issue by zhbi98** [peng-zhihui/ElectronBot#126]
我知道使用建模软件导出外壳 `DXF` 文件提供给 `PCB` 可以约定 `PCB` 板子的形状，我知道底面怎么做但是侧面怎么办？所以我的疑问是怎么通过导入结构设计文件的方式使得外壳侧边开口和 `PCB` 上接口位置对应起来。（比如外壳侧边 USB 开口和 PCB 板子上的 USB 接口契合）

**Comment by az666** [comment]
元器件都有三维模型的，导出PCB三维的时候，元器件的三维也已经出来了，设计外壳的时候就可以知道元器件的高低、大小、开孔位置。

**Comment by zhbi98** [comment]
> 元器件都有三维模型的，导出PCB三维的时候，元器件的三维也已经出来了，设计外壳的时候就可以知道元器件的高低、大小、开孔位置。

可是不是一般先设计外壳嘛，然后 `PCB` 形状跟着外壳形状走
