### ISSUE TITLE
禁用签名后手动更新驱动依然失败

### ISSUE THREAD

**Issue by az666** [peng-zhihui/ElectronBot#130]
![error](https://user-images.githubusercontent.com/32945694/161780346-6cb88396-454e-4c5d-911f-c9aec68d600f.gif)
1、禁用驱动强制签名，用命令行方式永久禁用
2、硬件焊接正常，接入PC可识别到未知设备
3、手动更新驱动，引导到对应文件夹（排除路径问题直接放到桌面）
4、瞬间扫描完后就退出显示“无法安装”

**Comment by peng-zhihui** [comment]
禁用完应该要重启才行的，我不太清楚你这个脚本禁用是否有效，我是进入设置的高级重启选项，然后选择禁用的

**Comment by az666** [comment]
高级重启来进行禁用驱动签名的操作也是试过的，就很奇怪，看群里也有其他朋友有一样的问题，按道理来讲安装驱动是纯PC端的操作，但是我换了另一台电脑也是如此。

**Comment by peng-zhihui** [comment]
那你试试用Zagdig安装libusb的驱动呢

**Comment by coolflyreg** [comment]
> 高级重启来进行禁用驱动签名的操作也是试过的，就很奇怪，看群里也有其他朋友有一样的问题，按道理来讲安装驱动是纯PC端的操作，但是我换了另一台电脑也是如此。

你可以参考下这个issue：https://github.com/peng-zhihui/ElectronBot/issues/122#issuecomment-1088847640

看你的动图里，也是有一个串口和一个ElectronBot@PZH，那么不出意外的话，这俩的硬件id后面都有&MI_0X的。就是这个不同，导致了驱动装不上。

你可以右键，属性，看下ElectronBot@PZH里硬件id是什么，然后改下BotDriver里的ElectronBot@PZH.inf文件里的DeviceId，改成一样的。然后再安装驱动，同时更新驱动的时候，选择手动选择已安装列表里的驱动，就可以装上。

**Comment by az666** [comment]
该问题已解决：拉取最新仓库编译烧录即可。
