### ISSUE TITLE
测试程序 显示连接正常，但无法显示图像

### ISSUE THREAD

**Issue by ljyws** [peng-zhihui/ElectronBot#132]
![J0}`D_44(Q` GJHIUWFE$I](https://user-images.githubusercontent.com/53010357/161888089-8de064e1-2294-4178-a8bf-cc868a0ba64d.png)

**Comment by ljyws** [comment]
图像还是花屏

**Comment by CWEIB** [comment]
#122

**Comment by az666** [comment]
> 驱动装好了，也显示连接了，一样的情况，走一步一个坑哈哈，目前lssues里面的所有奇葩问题我都遇到了

解决了，驱动搞好以后，记得烧录测试的hex文件来验证。或者自己把mincpp里面的舵机相关的操作注释下。
