### ISSUE TITLE
能否分享Fusion360的原文件？

### ISSUE THREAD

**Issue by hyansuper** [peng-zhihui/ElectronBot#14]
我想学学建模步骤以及曲面，谢谢

**Comment by ZhechengLiao** [comment]
在CAD那个文件夹里，有个step文件

**Comment by hyansuper** [comment]
> 在CAD那个文件夹里，有个step文件
> 
> 

step 文件是最终效果图。
我是说f3z格式的文件，里面记录了从无到有每一个建模步骤。因为我也在学fusion360

**Comment by hyansuper** [comment]
另外，齿轮建模用了什么插件吗？

**Comment by wenFrankieeee** [comment]
希望能开源360 建模源文件

**Comment by peng-zhihui** [comment]
可以，我共享了：https://a360.co/3t6CUMS
