### ISSUE TITLE
建议舵机添加通过iic或者单总线升级固件的功能

### ISSUE THREAD

**Issue by gcrisis** [peng-zhihui/ElectronBot#146]
只是个建议哈！
感觉后续如果升级固件通过swd有点不方便。
fpv穿越机的电调可以通过控制线升级固件，只需要一根线，我感觉这个项目也可以实现。

**Comment by az666** [comment]
理论上可以实现，可是依然逃不掉要先烧录一个bootloader呀，哈哈

**Comment by gcrisis** [comment]
> 固件升级为了避免变砖一般要求至少2倍APP的储存空间（所以可以回退），16K的Flash太小了，还要加上BL基本不可能放得下

是哈，我想的太简单了。

**Comment by gcrisis** [comment]
> 理论上可以实现，可是依然逃不掉要先烧录一个bootloader呀，哈哈

恩，不过烧一次就行，后边升级就不用拆舵机了。不过的确如稚晖君所说，空间才是硬伤。
