### ISSUE TITLE
卡在最后Unity无法同步动作的原因和解决办法

### ISSUE THREAD

**Issue by isSJ** [peng-zhihui/ElectronBot#158]
### 我的进度：
1.硬件焊接完成
2.usb、lcd调试通过
3.舵机逐个设置、联调通过

卡在打开Unity，可以显示摄像头，模型优先无法同步舵机动作。

### 原因：
stm32f405正式固件的Main函数中，有一段 :
```
 while (true)
    {
#if 0
        for (int p = 0; p < 4; p++)
        {
            // send joint angles
            for (int j = 0; j < 6; j++)
                for (int i = 0; i < 4; i++)
```

其实是接收USB数据、反馈舵机状态的。默认没有打开，未执行。

### 解决方案：
**#if 0 改为 #if 1**

### 附记：
写的如此正式，就是为了反讽自己过度关注硬件，实在太折磨了。第一次焊接，购买了大量工具，虚焊问题困扰许久。有些神经质了。遇到问题第一时刻认为是硬件问题。结果相对擅长的软件部分，过度依赖稚晖君了，没有独立思考。最终卡在了0和1上，很刺激。看到很多朋友都卡在这一步，或擅长硬件 或擅长软件 或边学边做。没关系。可以继续下一个坑了。

最后，感谢稚晖君，关注b站许久，终于没忍住。但是从动手中，学习到了很多新知识。感谢群友们耐心指点。

**Comment by regestday** [comment]
我们的不是这个问题 我的是单步调试的,我连摄像头都不显示。可以看这里  #142  我的截图

**Comment by wenFrankieeee** [comment]
原码默认是1， 你unity可以操作舵机了？

**Comment by az666** [comment]
> 我们的不是这个问题 我的是单步调试的,我连摄像头都不显示。可以看这里 #142 我的截图

看了你的情况，扎心了老铁，我的目前也是这样，硬件验证都是OK的，自己编译unity也是没有任何反应

**Comment by regestday** [comment]
我成了，上位机兼容性搞了快两个星期，不过方法不通用，问题还是出在opencv+unity兼容性
