### ISSUE TITLE
大佬是怎么将手势识别模块识别的指令转换成电脑的相应的操作的？

### ISSUE THREAD

**Issue by huixinxiaozi** [peng-zhihui/ElectronBot#160]
我想用stm32做一个比大佬差很多的小配件，但不知道怎么将手势识别得到的指令用来控制电脑。

**Comment by peng-zhihui** [comment]
了解一下AutoHotKey

**Comment by huixinxiaozi** [comment]
> 

大佬，我打算做一下你这个作品的分支，手势模块+单片机控制电脑的相应操作，我已经看了一点AutoHotKey，虽然c语言程序里面可以使用system(“start  ” )函数打开.ahk文件，但是发现在单片机里面的代码里面是不能用这样的函数进行的，我现在能想到的只能用串口通信进行与电脑信息的发送，但我又感觉串口通信与单片机通信无法达到视频中的现象，大佬能说一下你是怎么做的吗，我用的是stm32c8t6，因为现在是大一很多东西都不是很懂。

**Comment by peng-zhihui** [comment]
本来sdk就是在电脑上运行不是MCU上运行的，视频里说了

**Comment by huixinxiaozi** [comment]
> 本来sdk就是在电脑上运行不是MCU上运行的，视频里说了
抱歉啊，我才学单片机没多久，看视频的时候没有懂sdk到底是什么意思。

**Comment by huixinxiaozi** [comment]
我用ch9329模块做出来了，感谢
