### ISSUE TITLE
关于舵机的几个疑问

### ISSUE THREAD

**Issue by gcrisis** [peng-zhihui/ElectronBot#162]
1、i2c收到数据后都会立刻回传数据，除了读角度和速度以外，其他命令回传数据的目的是什么？可否将读写做成异步，主机根据需要读写，而不是必须读。之所以有这个问题是我在将i2c移植到ll库的时候用了dma，读写完全分开了，异步也能达到之前的效果，而且操作更加自由，所以想了解你的设计思路，看看我这样会导致什么问题？

2、while循环中有个判断CONFIG_RESTORE的分支，但是没有找到哪里会设置这个状态。

3、设置ID后可否立即生效，这样就不需要重启了，设置完可以直接使用。有一个潜在的问题是如果使用自定义的ID，设置时写和读的ID会变化，读回传需要使用修改后的地址，可能会对现有设置ID的代码造成影响。

**Comment by peng-zhihui** [comment]
1、STM32的硬件I2C有bug，最好是有一个完整的读写来回保证稳定性，没必要异步这里的读写速度很快的，而且异步不能保证数据是实时的反而不好
2、RESTORE就是一个flag，在main开头确认只要flag不是OK就会触发用默认参数覆盖配置
3、可以，需要修改I2C配置代码
