### ISSUE TITLE
jlink在clion上下载程序失败

### ISSUE THREAD

**Issue by yangyuwei5520** [peng-zhihui/ElectronBot#185]
![W }3S(_07C%H5`A@RW`4 MG](https://user-images.githubusercontent.com/73475956/169981060-2ac56116-8599-4345-bcd5-8546655bb08b.png)
![JS@1 9C6L%B1$AM AP_X8`8](https://user-images.githubusercontent.com/73475956/169981112-87c1286a-24f5-4ba4-9309-ffd3c0c22336.png)
![J_BBX T4B@X8@~C~C_K9ILC](https://user-images.githubusercontent.com/73475956/169981814-63f5c006-9f98-49f2-b292-713ca8857e3f.png)
这是我jink配置文件的内容，下载的时候就会报错误，但是我jlink驱动是安装成功的，这是怎么回事呢？

**Comment by peng-zhihui** [comment]
参考`openocd/scripts/board/xxx_jlink.cfg`
