### ISSUE TITLE
关于 usb 数据传输时为什么 512 大小的包需要传输两次的问题

### ISSUE THREAD

**Issue by Eilgnaw** [peng-zhihui/ElectronBot#186]
稚晖君,你好,我在尝试重写 lowlevel sdk的时候遇到屏幕显示整体偏移且有三个横线,后来查看源码发现在USBInterface.cpp 里的USB_BulkTransmit 里对 512 大小的包进行了第二次长度为 0 的传输,现在虽然显示正常了,但不理解这样做的原因是什么?希望能简单解答一下,谢谢.

**Comment by peng-zhihui** [comment]
libusb-0.x有点小bug，经测试我用libusb1.x就不用这样处理了

**Comment by Eilgnaw** [comment]
感谢回复.不过我现在用的是 1.0.26,依然有问题,后面我再测试一下.
