### ISSUE TITLE
烧录时报错Error: read version failed

### ISSUE THREAD

**Issue by Whering** [peng-zhihui/ElectronBot#209]
请问有大佬知道这是怎么回事吗，我纯萌新完全不懂这些，我甚至不确定有没有焊接好😭😭😭
![image](https://user-images.githubusercontent.com/52783054/180800666-b32fbd21-f24b-48d8-8a4d-f5fc1d01f978.png)

**Comment by PayenPan** [comment]
没有读取到CPU，先量5V和3.3V的供电有没有问题。首先供电永远不能短路。确保不短路上电，然后测试lp2992的out脚3.3V输出对不对。
![1658804191716](https://user-images.githubusercontent.com/41794546/180913453-f25e0e0d-fdb5-4cb6-96b7-fc0540fd0b25.jpg)
。
确保电源没有问题，才开始焊接cp2102，cpu，usb模块。最后焊接时钟（8MHZ和24MhZ的晶振）。不要虚焊，用万能表测芯片脚位和焊盘有没有短接，短接就没有虚焊。切记，5V对地，3.3V对地，5V对3.3V上电前一定要测试短路，有短路不可上电。要不然5v进CPU和USB，基本上CPU不是报废就是就是在报废的路上。

**Comment by Whering** [comment]
> 没有读取到CPU，先量5V和3.3V的供电有没有问题。首先供电永远不能短路。确保不短路上电，然后测试lp2992的out脚3.3V输出对不对。 ![1658804191716](https://user-images.githubusercontent.com/41794546/180913453-f25e0e0d-fdb5-4cb6-96b7-fc0540fd0b25.jpg) 。 确保电源没有问题，才开始焊接cp2102，cpu，usb模块。最后焊接时钟（8MHZ和24MhZ的晶振）。不要虚焊，用万能表测芯片脚位和焊盘有没有短接，短接就没有虚焊。切记，5V对地，3.3V对地，5V对3.3V上电前一定要测试短路，有短路不可上电。要不然5v进CPU和USB，基本上CPU不是报废就是就是在报废的路上。

感谢解答，供电没问题，cp2102也识别出来了，我初步测了下stm32芯片引脚应该也是通的，我现在怀疑是不烧录器的问题，我重新连了下导线后爆了别的问题，我重新买了个烧录器准备之后在试下。
