### ISSUE TITLE
奇怪，为什么我打不开本项目的STEP文件

### ISSUE THREAD

**Issue by wenFrankieeee** [peng-zhihui/ElectronBot#22]
我用123DESIGN 开 STEP 没问题，哥们这次项目STEP打开是空白。

**Comment by Sun-Shun** [comment]
用Autodesk Fusion 360

**Comment by wenFrankieeee** [comment]
> 用Autodesk Fusion 360

不行啊，我用360（个人版）试过，无法打开

**Comment by Sun-Shun** [comment]
我的可以，报错信息是什么，可以去网上找找

**Comment by wenFrankieeee** [comment]
谢谢，解决了，是文件下载问题

**Comment by Mars-Geek** [comment]
我将需要打印的文件都保存出来
[SolidWorks.zip](https://github.com/peng-zhihui/ElectronBot/files/8241086/SolidWorks.zip)
了

**Comment by song-hailong** [comment]
> 我将需要打印的文件都保存出来 [SolidWorks.zip](https://github.com/peng-zhihui/ElectronBot/files/8241086/SolidWorks.zip) 了

请问，这个打印文件里的“手臂推杆-右”是镜像来的吗？

**Comment by peng-zhihui** [comment]
是要镜像，不过我更新文件了，你pull一下就行

**Comment by Mars-Geek** [comment]
> 

对，我镜像的

**Comment by Mars-Geek** [comment]
> > 我将需要打印的文件都保存出来 [SolidWorks.zip](https://github.com/peng-zhihui/ElectronBot/files/8241086/SolidWorks.zip) 了
> 
> 请问，这个打印文件里的"手臂推杆-右"是镜像来的吗？

对，是镜像来的
