### ISSUE TITLE
CP2102不识别

### ISSUE THREAD

**Issue by nmguoying** [peng-zhihui/ElectronBot#232]
总是显示无法识别的USB设备，看不到COM口，可能的原因是什么？
CP2102驱动装的没有问题，用其他现成的2102板子试过了
供电电压没有问题
芯片是优信电子买的
![20221127114213](https://user-images.githubusercontent.com/69742013/204118256-54f170e6-2bce-4b9a-af7f-04c1d1452adb.jpg)

**Comment by nmguoying** [comment]
虚焊问题，解决了

**Comment by sakurafly123** [comment]
是哪里虚焊，我也识别不了
