### ISSUE TITLE
请问摄像头是用什么模块？用什么协议

### ISSUE THREAD

**Issue by jeremyvirtue** [peng-zhihui/ElectronBot#24]
仔细看了原理图，传感器板只有手势传感器和6轴，主控板 SD+USBTTL+高速USB+TTF，找不到摄像头的口，难道是用USB来驱动摄像头？

**Comment by vincent-vinf** [comment]
![image](https://user-images.githubusercontent.com/54889985/158060323-4a5728ce-b65a-4a51-be3a-24d4fc7d5f2c.png)
看SensorBoard原理图，可以发现使用了一个HS8836A作为usb hub 连接了摄像头

**Comment by vincent-vinf** [comment]
![image](https://user-images.githubusercontent.com/54889985/158060792-a6c0bae1-1045-4e1b-bf34-dd7c4b221792.png)
 理了一下，应该是这样的关系

**Comment by jeremyvirtue** [comment]
> ![image](https://user-images.githubusercontent.com/54889985/158060792-a6c0bae1-1045-4e1b-bf34-dd7c4b221792.png) 理了一下，应该是这样的关系

![image](https://user-images.githubusercontent.com/45451508/158064722-f70a2ff1-ef67-4ddf-b27d-eca85b4ef1f2.png)
看了一下资料 ，up应该是用了这个芯片，那我大概懂了，USB协议驱动摄像头。是这样码

**Comment by peng-zhihui** [comment]
我用的这个：https://item.taobao.com/item.htm?id=567717780577
你也可以用别的USB摄像头，里面塞得下就行
