### ISSUE TITLE
【求助】SensorBoard 显示"无法识别的USB设备"

### ISSUE THREAD

**Issue by weijieyong** [peng-zhihui/ElectronBot#241]
SensorBoard连接电脑时，显示"无法识别的USB设备"，
请问能告诉我这里可能的原因吗？
- 供电电压没有问题

![sensorboard](https://user-images.githubusercontent.com/29274892/230878586-ba694c5f-3819-488c-84e9-014b1288269e.jpg)
![image](https://user-images.githubusercontent.com/29274892/230878779-dfa4893d-bfcd-40bf-8b89-9b0fa396966e.png)

**Comment by VendettaMask** [comment]
来信已收，谢谢！

**Comment by qiang-lsh** [comment]
八成是USB-HUB芯片的问题

**Comment by qiang-lsh** [comment]
USB-HUB芯片和外围电路查一下，USB-HUB芯片和fpc座子通不通

**Comment by weijieyong** [comment]
谢谢回复，检查了USB-HUB芯片(HS8836A)和fpc座子没问题，也没有虚焊问题。
请问有没有可能是驱动没装的问题？

**Comment by qiang-lsh** [comment]
主控板上USB3300这个芯片是需要装稚晖君给的驱动，这个板焊接正常上电就会有显示的。叫通用USB集线器

**Comment by Kevin75311** [comment]
你好，請問你是用哪一家的晶元，我連續換了好幾個都一樣無法辨識。

**Comment by VendettaMask** [comment]
来信已收，谢谢！

**Comment by BLDC888** [comment]
您好：你的来信我已收到，我会尽快处理的。

**Comment by sakurafly123** [comment]
> 谢谢，换了一个新的USB-HUB芯片，正常识别了

这个是HS8836吗
