### ISSUE TITLE
【求助】  cp2102 一直未识别到

### ISSUE THREAD

**Issue by sakurafly123** [peng-zhihui/ElectronBot#247]
楼主之前的焊的板子，cp2102 一直未识别到
（1）3.3 和gnd没有短路
 （2）看上去没有虚焊，但是因为没有引脚也不能百分百确定
 （3）传感器到 大脑板子的，插座我检查了，线路是通，但还是有个疑问，会不会加热把座子焊坏了，虽然是通的，但是其实fpc座子还是有问题
 （4）因为在焊接的时候，用焊烙铁对着fpc座子一直挂锡，一直挂了快20分钟，担心把pcb烧坏了，或者芯片烧坏了
 （5）cp2102 第一块板子识别的了，并安装了驱动，现在是重新焊接的第二块板子，已经装了驱动会不会让电脑不识别
  （6）用的是小卡的板子，不用排线链接大脑，能够看到usb集线器
有没有谁知道怎么排查，如果手把手帮助成功能够成功识别，可以有偿v你吃顿肯德基，或者谁会，我寄快递过去，帮我检测一下，在这上面花了好多时间了

**Comment by VendettaMask** [comment]
来信已收，谢谢！

**Comment by sakurafly123** [comment]
> 来信已收，谢谢！

小哥知道怎么回事吗

**Comment by phn02** [comment]
> 楼主之前的焊的板子，cp2102 一直未识别到 （1）3.3 和gnd没有短路 （2）看上去没有虚焊，但是因为没有引脚也不能百分百确定 （3）传感器到 大脑板子的，插座我检查了，线路是通，但还是有个疑问，会不会加热把座子焊坏了，虽然是通的，但是其实fpc座子还是有问题 （4）因为在焊接的时候，用焊烙铁对着fpc座子一直挂锡，一直挂了快20分钟，担心把pcb烧坏了，或者芯片烧坏了 （5）cp2102 第一块板子识别的了，并安装了驱动，现在是重新焊接的第二块板子，已经装了驱动会不会让电脑不识别 （6）用的是小卡的板子，不用排线链接大脑，能够看到usb集线器 有没有谁知道怎么排查，如果手把手帮助成功能够成功识别，可以有偿v你吃顿肯德基，或者谁会，我寄快递过去，帮我检测一下，在这上面花了好多时间了

还没搞定吗，兄弟

**Comment by sakurafly123** [comment]
> > 楼主之前的焊的板子，cp2102 一直未识别到 （1）3.3 和gnd没有短路 （2）看上去没有虚焊，但是因为没有引脚也不能百分百确定 （3）传感器到 大脑板子的，插座我检查了，线路是通，但还是有个疑问，会不会加热把座子焊坏了，虽然是通的，但是其实fpc座子还是有问题 （4）因为在焊接的时候，用焊烙铁对着fpc座子一直挂锡，一直挂了快20分钟，担心把pcb烧坏了，或者芯片烧坏了 （5）cp2102 第一块板子识别的了，并安装了驱动，现在是重新焊接的第二块板子，已经装了驱动会不会让电脑不识别 （6）用的是小卡的板子，不用排线链接大脑，能够看到usb集线器 有没有谁知道怎么排查，如果手把手帮助成功能够成功识别，可以有偿v你吃顿肯德基，或者谁会，我寄快递过去，帮我检测一下，在这上面花了好多时间了
> 
> 还没搞定吗，兄弟

搞定了，但是现在又出现新的问题，未知设备没有识别到
