### ISSUE TITLE
SensorBoard 电阻R3过热发红，被烧的问题

### ISSUE THREAD

**Issue by jxyjason** [peng-zhihui/ElectronBot#248]
我最近在焊接sensorboard，焊好之后上电，发现和USB芯片相连的R3迅速升温，然后发红冒烟。检查了电路没有短路，R3电阻测了一下为5Ω左右。测量了很多通路都是通的，然后3v3的芯片也没有短路。
有没有大佬知道可能的问题？
![FAS@Z`T7UW1(U)H (E7R(3L](https://github.com/peng-zhihui/ElectronBot/assets/90661453/fd2d71df-c8e8-441a-8130-c516119ed7df)

**Comment by VendettaMask** [comment]
来信已收，谢谢！

**Comment by jxyjason** [comment]
解决了，原因是电阻购买时候买成额定功率太小的，应该买大一点的
