### ISSUE TITLE
舵机不转

### ISSUE THREAD

**Issue by jxyjason** [peng-zhihui/ElectronBot#255]
大家好，我的舵机板子焊好后，使用clion下载程序，然后主板下载舵机测试程序后舵机不转
使用STM32 ST-LINK Utility时候，烧录器一直红蓝灯闪烁，过段时间之后显示无法连接。
焊了好几块板子都是这样，感觉可能是clion没有烧录进去或者是焊接哪儿有问题。

使用的原版pcb，测试了stm32上各个引脚都和对应位置联通，而且有3v3电压，舵机也换了两个，还是不行。

芯片是030，烧录的程序是稚晖君github上的

请问还可能是什么原因

**Comment by jxyjason** [comment]
解决了，要配置stlink为软件复位

**Comment by VendettaMask** [comment]
来信已收，谢谢！
