### ISSUE TITLE
ElectronBot的F405的外部晶振未使能

### ISSUE THREAD

**Issue by leazer** [peng-zhihui/ElectronBot#27]
看到主控PCB中绘制有8Mhz村田晶振，但是cubeMX和代码中关于时钟树的配置部分，启用的是HSI哈，也就是目前没有用到外部那颗8Mhz晶振作为时钟源哈。
![微信截图_20220314003207](https://user-images.githubusercontent.com/16811146/158069443-fdb19469-ed82-43d8-9663-f39f05fa4813.png)
![微信截图_20220314003136](https://user-images.githubusercontent.com/16811146/158069422-6854f8bf-134c-46fc-8485-8f86d36bd241.png)
![微信截图_20220314003304](https://user-images.githubusercontent.com/16811146/158069478-0d992f5e-ca49-4ab9-938b-381d2e6c4355.png)

**Comment by peng-zhihui** [comment]
好像是漏了，我修复一下
