### ISSUE TITLE
SensorBoard上有多余的VBUS_IN的一条走线

### ISSUE THREAD

**Issue by coolflyreg** [peng-zhihui/ElectronBot#28]
首先感谢稚晖君开源的分支工程Y(^_^)Y

SensorBoard上的FPC座的VBUS_IN接脚右侧的一根线，看起来是多余的，请检查。以下是AD中的截图

<img width="866" alt="image" src="https://user-images.githubusercontent.com/4011564/158090466-f46f63b4-1a50-4377-ba10-418ce4102845.png">
<img width="784" alt="image" src="https://user-images.githubusercontent.com/4011564/158090511-2d31baa7-2b48-4825-97cf-7fa9b1afe9ea.png">
<img width="761" alt="image" src="https://user-images.githubusercontent.com/4011564/158090534-71d3a4d7-2e3c-492e-a51e-5a5f4e100930.png">

**Comment by peng-zhihui** [comment]
这个是当时替换USB-HUB芯片忘了删了，不影响功能，我修复一下
