### ISSUE TITLE
PAJ7620U2手势识别模式问题

### ISSUE THREAD

**Issue by ggysl** [peng-zhihui/ElectronBot#37]
感谢大佬的开源，想请问一下PAJ7620U2手势识别是使用的Gesture Mode还是Image Mode，我注意到原理图中只连接了iic，是使用的Gesture Mode嘛？那是如何识别数123的手势呢？
没有找到处理PAJ7620U2的代码，还请告知，感谢！！

**Comment by vincent-vinf** [comment]
可能是结合了摄像头的图像

**Comment by peng-zhihui** [comment]
手势模式，主要识别功能是靠摄像头实现的，PAJ7620U2只能识别若干很简单的手势。
