### ISSUE TITLE
Robodk和KUKA机器人的连接问题

### ISSUE THREAD

**Issue by songsong12345687** [peng-zhihui/ElectronBot#59]
我用robodk软件和KUKA机器人连接，结果实物机器人可以控制虚拟机器人，但是虚拟机器人无法控制实物机器人，请问怎么解决这个通讯问题？

**Comment by peng-zhihui** [comment]
这个问题与本仓库项目无关不要在这里提交

**Comment by peng-zhihui** [comment]
而且你问的也太泛了，这种问题原因太多别人不可能帮你debug的

**Comment by songsong12345687** [comment]
谢谢您的回复！不好意思打扰了，我遇到这个难题一时解决不了才向您请教的，我再想别的办法解决吧
