### ISSUE TITLE
请问USBInterface.dll的源码，或这个USBInterface.dll从哪里查看资料呢

### ISSUE THREAD

**Issue by coolflyreg** [peng-zhihui/ElectronBot#61]
请问USBInterface.dll的源码，或这个USBInterface.dll从哪里查看资料呢

**Comment by peng-zhihui** [comment]
我自己写的，基于libusb，这个二次开发不涉及修改所以我没有上传

**Comment by peng-zhihui** [comment]
就算USB设备管理和底层数据的Bulk读写，需要给个邮箱我发你

**Comment by coolflyreg** [comment]
> 就是USB设备管理和底层数据的Bulk读写，需要给个邮箱我发你

十分感谢，我的邮箱：coolflyr_reg@126.com

**Comment by erikaemma** [comment]
不方便开源吗大佬？

**Comment by erikaemma** [comment]
同求一份好吗？

**Comment by BalrogCat** [comment]
@peng-zhihui 
同是 macOS 同求一份 USBInterface 源码，邮箱 1370908926@qq.com

**Comment by QDDCoder** [comment]
@peng-zhihui
同是 macOS 同求一份 USBInterface 源码，邮箱 [CodingClearLove@gmail.com](mailto:CodingClearLove@gmail.com)

**Comment by yeliheng-010** [comment]
同是 macOS 同求一份 USBInterface 源码，邮箱 1534503231@qq.com

**Comment by VendettaMask** [comment]
来信已收，谢谢！

**Comment by QDDCoder** [comment]
> > 就是USB设备管理和底层数据的Bulk读写，需要给个邮箱我发你
> 
> 十分感谢

请问大佬收到了吗，能否转发我一分

**Comment by VendettaMask** [comment]
来信已收，谢谢！

**Comment by BLDC888** [comment]
您好：你的来信我已收到，我会尽快处理的。
