### ISSUE TITLE
我用STM32CubeMX生成了工程，但其实很难编译通过

### ISSUE THREAD

**Issue by idnewfeel** [peng-zhihui/ElectronBot#66]
我用STM32Cubemx生成了MDK的工程，加上了C++编译，以及C99模式，生成的代码中，main.cpp和mian.c 以及usb_cdc_if.cpp和usb_cdc_if.c相互重叠，FreeRTOS源码和C++部分代码报了大量错误。看来需要尝试clion 来编译了。

**Comment by Mars-Geek** [comment]
求一份编译好的hex，平时keil用的多，其他编译器不会用

**Comment by peng-zhihui** [comment]
仔细看README写的编译说明，USB相关文件是要替换的，STM32CubeMX只适合第一次生成代码，后续修改了用户代码很多都会被覆盖。

**Comment by jinyi7016** [comment]
可以把clion的工程转换成stm32cubeide的工程，可以参考[点这里](https://blog.csdn.net/jinyi7016/article/details/123494319?spm=1001.2014.3001.5502)

**Comment by idnewfeel** [comment]
> 可以把clion的工程转换成stm32cubeide的工程，可以参考[点这里](https://blog.csdn.net/jinyi7016/article/details/123494319?spm=1001.2014.3001.5502)

写的很详细，晚上回去看看

**Comment by idnewfeel** [comment]
> 仔细看README写的编译说明，USB相关文件是要替换的，STM32CubeMX只适合第一次生成代码，后续修改了用户代码很多都会被覆盖。而且估计你Keil里也没有添加我自己的代码，工程里根本不完整。

嗯，UP的代码我确实是添加了。我想大概和你说的一样，可能是生成的文件被替换掉了，

**Comment by cedar-zhangyongchao** [comment]
楼主KEIL的解决了吗
