### ISSUE TITLE
请问SD卡槽在哪里购买的呀

### ISSUE THREAD

**Issue by zhoubin-datareachable** [peng-zhihui/ElectronBot#87]
![image](https://user-images.githubusercontent.com/80082695/159153094-08ab6e66-7203-43de-b632-545e010f24f2.png)

**Comment by zhoubin-datareachable** [comment]
淘宝找了一圈没找到

**Comment by zhoubin-datareachable** [comment]
help me！！！！！

**Comment by 7i7ian** [comment]
找的不仔细，有的一模一样

**Comment by zhoubin-datareachable** [comment]
> 找的不仔细，有的一模一样
能给个链接吗，谢谢了

**Comment by 7i7ian** [comment]
tb搜店铺金航通电子商行，我是在他家买的
----- 原始邮件 -----
发件人：zhoubin-datareachable ***@***.***>
收件人：peng-zhihui/ElectronBot ***@***.***>
抄送人：7i7ian ***@***.***>,  Comment ***@***.***>
主题：Re:_[peng-zhihui/ElectronBot]_请问SD卡槽在哪里购买的呀_(Issue_#87)
日期：2022年03月20日 16点06分





找的不仔细，有的一模一样


能给个链接吗，谢谢了





&mdash;

**Comment by ymm135** [comment]
[[https://item.szlcsc.com/3757184.html?fromZone=s_s__%2522tf%25E5%258D%25A1%25E5%25BA%25A7%25208p%2520%25E6%258B%2594%25E6%258F%2592%25E5%25BC%258F%2522&spm=sc.gbn.xh13.zy.t&lcsc_vid=TlULVlFeFABaXlwAQ1NWUVBURlYNUVECRwANXlIFTlYxVlNQRVlaVldSQFZeUjsOAxUeFF5JWBIBSRccGwIdBEoFGAxBAAgJFQACSQwSGg0%3D](拔插式 MicroSD卡(TF卡) )](https://item.szlcsc.com/3757184.html?fromZone=s_s__%2522tf%25E5%258D%25A1%25E5%25BA%25A7%25208p%2520%25E6%258B%2594%25E6%258F%2592%25E5%25BC%258F%2522&spm=sc.gbn.xh13.zy.t&lcsc_vid=TlULVlFeFABaXlwAQ1NWUVBURlYNUVECRwANXlIFTlYxVlNQRVlaVldSQFZeUjsOAxUeFF5JWBIBSRccGwIdBEoFGAxBAAgJFQACSQwSGg0%3D)

拔插式 MicroSD卡(TF卡) 卡座 品牌名称：Amphenol

<img width="1654" height="984" alt="Image" src="https://github.com/user-attachments/assets/7f112b9f-42c0-4596-8e0a-b9441e73876b" />

**Comment by VendettaMask** [comment]
来信已收，谢谢！
