### ISSUE TITLE
Openpose的demo应用有开源吗

### ISSUE THREAD

**Issue by fzwwj95** [peng-zhihui/ElectronBot#9]

**Comment by fzwwj95** [comment]
Openpose的demo应用有开源吗，想学习下

**Comment by peng-zhihui** [comment]
https://github.com/CMU-Perceptual-Computing-Lab/openpose 这个仓库里有demo

**Comment by fzwwj95** [comment]
> https://github.com/CMU-Perceptual-Computing-Lab/openpose 这个仓库里有demo

就只是利用他的摄像头，显示什么只是再发到屏幕吧

**Comment by peng-zhihui** [comment]
是的
