### ISSUE TITLE
请问4-CADModel里的文件打不开，也下载不了是怎么回事

### ISSUE THREAD

**Issue by 1125106079** [peng-zhihui/ElectronBot#93]
请问4-CADModel里的文件打不开，也下载不了是怎么回事

**Comment by 7i7ian** [comment]
fusion 360

**Comment by peng-zhihui** [comment]
检查自己网络问题，实在不行可以去Gitee的镜像仓库下载

**Comment by 1125106079** [comment]
> 检查自己网络问题，实在不行可以去Gitee的镜像仓库下载

好的，多谢

**Comment by 1125106079** [comment]
> 检查自己网络问题，实在不行可以去Gitee的镜像仓库下载



> 融合360

没有iphone
