### ISSUE TITLE
[FR]舵机指令说明

### ISSUE THREAD

**Issue by kaidegit** [peng-zhihui/ElectronBot#98]
请问有没有意向写一写舵机的i2c指令说明

**Comment by peng-zhihui** [comment]
> 从代码里整理出来的指令内容说明： ![](https://camo.githubusercontent.com/3dde7fb9435f1a79aa705360835cd3dbfa7245562db021a9e9dc016d55828e84/68747470733a2f2f69302e6864736c622e636f6d2f6266732f616c62756d2f306332643064616166653532386331656137633636653430313964393064383065373161363436642e706e67)

感谢整理，表格很漂亮~
